### ISSUE TITLE
Shape inconsitency whikle training on bdd100k

### ISSUE THREAD

**Issue by learnermaxRL** [cscribano/CERBERUS#4]
Traceback (most recent call last):
  File "compressor.py", line 260, in <module>
    trainer_run()
  File "compressor.py", line 211, in trainer_run
    trainer.fit(model, train_loader, val_loader)
  File "/home/inferno/anaconda3/envs/cerberus/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
    self._call_and_handle_interrupt(
  File "/home/inferno/anaconda3/envs/cerberus/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/inferno/anaconda3/envs/cerberus/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/inferno/anaconda3/envs/cerberus/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run
    results = self._run_stage()
  File "/home/inferno/anaconda3/envs/cerberus/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "/home/inferno/anaconda3/envs/cerberus/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_train
    self._run_sanity_check()
  File "/home/inferno/anaconda3/envs/cerberus/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1411, in _run_sanity_check
    val_loop.run()
  File "/home/inferno/anaconda3/envs/cerberus/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/inferno/anaconda3/envs/cerberus/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 154, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/inferno/anaconda3/envs/cerberus/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/inferno/anaconda3/envs/cerberus/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 127, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/inferno/anaconda3/envs/cerberus/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 222, in _evaluation_step
    output = self.trainer._call_strategy_hook("validation_step", *kwargs.values())
  File "/home/inferno/anaconda3/envs/cerberus/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1763, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/inferno/anaconda3/envs/cerberus/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 344, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "compressor.py", line 118, in validation_step
    preds = self.forward(img)
  File "compressor.py", line 92, in forward
    pred = self.backbone(img)
  File "/home/inferno/anaconda3/envs/cerberus/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/inferno/Downloads/loconav/CERBERUS/models/cerberus.py", line 78, in forward
    scn_out = self.head_scn(small, argmax=inference)
  File "/home/inferno/anaconda3/envs/cerberus/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/inferno/Downloads/loconav/CERBERUS/models/heads.py", line 96, in forward
    w_pred, s_pred, t_pred = torch.split(x, self.cls_splits, 1)
  File "/home/inferno/anaconda3/envs/cerberus/lib/python3.8/site-packages/torch/functional.py", line 189, in split
    return tensor.split(split_size_or_sections, dim)
  File "/home/inferno/anaconda3/envs/cerberus/lib/python3.8/site-packages/torch/_tensor.py", line 611, in split
    return super(Tensor, self).split_with_sizes(split_size, dim)
RuntimeError: start (14) + length (4) exceeds dimension size (16).

**Comment by cscribano** [comment]
The file `compressor.py` is not part of this repo, please provide proper information about the issue.

**Comment by learnermaxRL** [comment]
i was working on model pruning,and the file is directly calling the trainer function just like main.py
